site_name: OpenTECR Schema
site_description: contains the code for the schema of the openTECR database
site_author: OpenTECR developers
site_url: https://opentecr-schema.readthedocs.io/

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.top
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
      default_handler: python
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rgiessman
      name: OpenTECR developers

copyright: Copyright &copy 2023 OpenTECR developers

repo_url: https://github.com/rgiessman/opentecr-schema
repo_name: rgiessman/opentecr-schema

watch:
  - src/opentecr
